Роутинг
lyolishe/Asteroids pull request #13
Opened 2020-12-20 15:19 UTC by artstrelb

2020-12-20 16:35 UTC, mdsdimat approved these changes

2020-12-21 09:38 UTC, lyolishe requested changes
С самим роутом всё оке, стоит только поставить редирект на логин, и сделать лейаут

2020-12-21 09:38 UTC, lyolishe commented on src/App.tsx
> +                <nav>
Необходимо написать лейаут - компонент, в который в последствии все дети будут от свича складываться.
Но т.к. мы пользуемся ant design, нет необходимости писать его. Есть готовые компоненты https://ant.design/docs/spec/navigation

2020-12-21 09:38 UTC, lyolishe commented on src/App.tsx
> +                    <Route>Здесь будет 404</Route>
Для обработки битой ссылки лучше использовать компонент <Redirect />(https://reactrouter.com/web/api/Redirect).
Но, я думаю, лучше редиректить не на 404 а на страницу логина, чтобы пользак вообще не видел ошибки в приложении)

2020-12-22 07:41 UTC, pashakhorikov commented on src/App.tsx
> +                    <Route>Здесь будет 404</Route>
А что думает @mdsdimat на эту тему?

2020-12-24 06:32 UTC, mdsdimat commented on src/App.tsx
> +                    <Route>Здесь будет 404</Route>
Согласен, мы обсуждали это на созвоне.

2020-12-24 12:31 UTC, lyolishe approved these changes

2020-12-24 13:42 UTC, mdsdimat approved these changes

2020-12-24 14:28 UTC, artstrelb commented on src/App.tsx
> +                    <Route>Здесь будет 404</Route>
Поправил

2020-12-24 14:29 UTC, artstrelb commented on src/App.tsx
> +                <nav>
Подключил Layout и меню от antd

2020-12-26 15:15 UTC, merged